'use strict';
const $=id=>document.getElementById(id);const num=id=>Number($(id)?.value);
function setResult(id,text,error=false){const el=$(id);if(!el)return;el.textContent=text;el.classList.toggle('error',error)}
function validScore(v){return Number.isFinite(v)&&v>=0&&v<=100}function validPositiveInt(v){return Number.isInteger(v)&&v>0}
function calcAverage(){const raw=$('scores').value.trim();if(!raw)return setResult('result','점수를 입력하세요.',true);const parts=raw.split(',').map(x=>x.trim());if(parts.some(x=>x===''||!/^(?:\d+(?:\.\d+)?|\.\d+)$/.test(x)))return setResult('result','점수는 쉼표로 구분해 입력하세요. 예: 87, 92, 76',true);const values=parts.map(Number);if(values.some(v=>!validScore(v)))return setResult('result','점수는 0점부터 100점 사이여야 합니다.',true);const avg=values.reduce((a,b)=>a+b,0)/values.length;setResult('result',`평균 ${avg.toFixed(2)}점 · ${values.length}개 점수`)}
function calcRank(type){const r=num('rank'),n=num('total');if(!validPositiveInt(r)||!validPositiveInt(n)||r>n)return setResult('result','석차와 전체 인원을 양의 정수로 입력하고, 석차가 전체 인원을 넘지 않게 해주세요.',true);const p=r/n*100;if(type===0)return setResult('result',`상위 약 ${p.toFixed(2)}%`);const g=type===5?(p<=10?1:p<=34?2:p<=66?3:p<=90?4:5):(p<=4?1:p<=11?2:p<=23?3:p<=40?4:p<=60?5:p<=77?6:p<=89?7:p<=96?8:9);setResult('result',`상위 약 ${p.toFixed(2)}% · 예상 ${g}등급`)}
function calcPerformance(){const a=num('examScore'),aw=num('examWeight'),b=num('taskScore'),bw=num('taskWeight');if(!validScore(a)||!validScore(b)||![aw,bw].every(Number.isFinite)||aw<0||bw<0||aw>100||bw>100)return setResult('result','점수는 0~100점, 반영비율은 0~100%로 입력하세요.',true);if(Math.abs(aw+bw-100)>1e-9)return setResult('result','시험과 수행평가 반영비율 합계가 100%가 되게 입력하세요.',true);setResult('result',`최종 환산점수 ${((a*aw+b*bw)/100).toFixed(2)}점`)}
function calcGoal(){const c=num('current'),w=num('weight'),g=num('target');if(!validScore(c)||!validScore(g)||!Number.isFinite(w)||w<=0||w>100)return setResult('result','현재 점수·목표 점수는 0~100점, 반영비율은 0~100%로 입력하세요.',true);const x=(g-c*(1-w/100))/(w/100);if(x>100)return setResult('result',`필요 점수 ${x.toFixed(1)}점 · 100점을 넘어 목표 달성이 어렵습니다.`,true);if(x<=0)return setResult('result','현재 점수만으로 목표점수에 이미 도달할 수 있습니다.');setResult('result',`다음 시험에 필요한 점수 ${x.toFixed(1)}점`)}
function calcStudy(){const raw=$('times').value.trim();if(!raw)return setResult('result','공부시간을 입력하세요.',true);let total=0;for(const item of raw.split(',')){const p=item.trim().split(':');if(p.length!==2||!/^[0-9]+$/.test(p[0])||!/^[0-9]+$/.test(p[1]))return setResult('result','형식은 1:30, 2:20처럼 입력하세요.',true);const h=Number(p[0]),m=Number(p[1]);if(m>59)return setResult('result','분은 0~59 사이여야 합니다.',true);total+=h*60+m}setResult('result',`총 공부시간 ${Math.floor(total/60)}시간 ${total%60}분`)}
function calcPlan(){const d=num('days'),h=num('hours');if(!Number.isFinite(d)||!Number.isInteger(d)||d<=0||!Number.isFinite(h)||h<0||h>24)return setResult('result','남은 일수는 1일 이상 정수, 하루 공부시간은 0~24시간으로 입력하세요.',true);setResult('result',`확보 가능한 공부시간 ${(d*h).toFixed(1)}시간`)}
function calcDday(){const value=$('date').value;if(!value)return setResult('result','시험 날짜를 선택하세요.',true);const today=new Date();today.setHours(0,0,0,0);const target=new Date(value+'T00:00:00');const diff=Math.round((target-today)/86400000);setResult('result',diff>0?`D-${diff}`:diff===0?'D-Day':`D+${Math.abs(diff)}`)}
function calcChars(){const s=$('text').value;setResult('result',`${s.length.toLocaleString()}자 · 공백 포함 / ${s.replace(/\s/g,'').length.toLocaleString()}자 · 공백 제외`)}
function neisBytes(s){let b=0;for(const ch of s){if(ch==='\n'||ch==='\r'||/[\x00-\x7F]/.test(ch))b+=1;else b+=3}return b}function calcBytes(){const s=$('text').value;setResult('result',`${neisBytes(s).toLocaleString()}B · ${s.length.toLocaleString()}자`)}
function setupTabs(){document.querySelectorAll('.tab').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(b=>{b.classList.remove('active');b.setAttribute('aria-selected','false')});document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));btn.classList.add('active');btn.setAttribute('aria-selected','true');const panel=$(btn.dataset.target);if(panel)panel.classList.add('active');try{localStorage.setItem('studytools-tab',btn.dataset.target)}catch(e){}}));try{const saved=localStorage.getItem('studytools-tab');const btn=document.querySelector(`.tab[data-target="${saved}"]`);if(btn)btn.click()}catch(e){}}
function setupSearch(){const input=$('toolSearch');if(!input)return;input.addEventListener('input',()=>{const q=input.value.trim().toLowerCase();document.querySelectorAll('.panel.active .card').forEach(card=>{card.hidden=q&&!card.textContent.toLowerCase().includes(q)});const empty=$('emptyState');const visible=[...document.querySelectorAll('.panel.active .card')].some(c=>!c.hidden);if(empty)empty.style.display=visible?'none':'block'})}
function setupToday(){const el=$('todayText');if(el){const d=new Date();el.textContent=`오늘 ${d.getMonth()+1}월 ${d.getDate()}일 기준`}}
function setupSubjects(){const box=$('subjectRows');if(!box)return;const add=()=>{const row=document.createElement('div');row.className='subject-row';row.innerHTML='<input class="subject-name" aria-label="과목명" placeholder="예: 국어"><input class="subject-score" aria-label="점수" inputmode="decimal" type="number" min="0" max="100" step="0.1" placeholder="90"><input class="subject-weight" aria-label="반영비율 또는 가중치" inputmode="decimal" type="number" min="0.01" max="100" step="0.01" placeholder="1"><button class="remove-subject" type="button" aria-label="과목 삭제">×</button>';row.querySelector('.remove-subject').addEventListener('click',()=>{if(box.children.length>1)row.remove();else setResult('subjectResult','최소 1개 과목은 남겨주세요.',true)});box.appendChild(row)};const reset=()=>{box.innerHTML='';add();add();add();setResult('subjectResult','과목을 1개 이상 입력하세요.')};const calc=()=>{const rows=[...box.children],items=[];for(const row of rows){const name=row.querySelector('.subject-name').value.trim(),score=Number(row.querySelector('.subject-score').value),weight=Number(row.querySelector('.subject-weight').value);if(!name&&!Number.isFinite(score)&&!Number.isFinite(weight))continue;if(!name||!validScore(score)||!Number.isFinite(weight)||weight<=0||weight>100)return setResult('subjectResult','과목명, 점수(0~100), 가중치(0보다 크고 100 이하)를 올바르게 입력하세요.',true);items.push({name,score,weight})}if(!items.length)return setResult('subjectResult','과목을 1개 이상 입력하세요.',true);const total=items.reduce((a,x)=>a+x.weight,0),avg=items.reduce((a,x)=>a+x.score*x.weight,0)/total;setResult('subjectResult',`가중 평균 ${avg.toFixed(2)}점 · ${items.length}과목 · 가중치 합계 ${total.toFixed(2)}`)};$('addSubject').addEventListener('click',add);$('resetSubjects').addEventListener('click',reset);$('calcSubjects').addEventListener('click',calc);reset()}
function setupTimer(){const display=$('timerDisplay');if(!display)return;let seconds=25*60,running=false,id=null,sessions=0;const render=()=>{const m=Math.floor(seconds/60),s=seconds%60;display.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`};const start=()=>{if(running)return;running=true;$('timerStart').textContent='일시정지';id=setInterval(()=>{if(seconds>0){seconds--;render()}else{clearInterval(id);running=false;sessions++;$('timerStart').textContent='시작';$('sessionCount').textContent=sessions;seconds=25*60;render()}},1000)};const toggle=()=>{if(running){clearInterval(id);running=false;$('timerStart').textContent='계속'}else start()};const reset=()=>{clearInterval(id);running=false;seconds=25*60;$('timerStart').textContent='시작';render()};$('timerStart').addEventListener('click',toggle);$('timerReset').addEventListener('click',reset);render()}
window.addEventListener('DOMContentLoaded',()=>{setupTabs();setupSearch();setupToday();setupSubjects();setupTimer()});
